### PR TITLE
[WIP] [NEED DISCUSSION] Loader

### PR DESCRIPTION
**Pull request by stegben**
A loader for importing saved model. Specialized for serving format.

## Functionality
- Load the saved model back to python session.
- Modify the input of loaded model, and return new signature_def_map
- Modify the output of loaded model, and return new signature_def_map

## Proposed Usage

1. Purely load:
```python
loader = Loader(saved_model_path)
with graph.as_default():
    loader.load()
```

2. Load with existing input and output:
3. Save serving format with modified graph and new signature def.

## TODO
- [ ] Extract meta_graph_def from the saved model

### CODE REVIEW

**Comment by SoluMilken** [comment]
如果 是 frozen model load 法會不一樣？

**Comment by SoluMilken** [comment]
We expect the Loader can ...
1. restore a re-trainable graph, fit again and predict?
2. restore a frozen graph and predict?
3. be a wrapper to keep users from controlling client on their own?

**Comment by stegben** [comment]
1.2. It depends on how the user save the model. If it is saved in frozen mode, then its variables are not trainable. Also, whether a saved model can be trained is determined by the signature def map. It has nothing to do with the loader.

3. Nope, it just load the model into a session.

**Comment by stegben** [comment]
done in #33

**Pull request closed without merging**
